### ISSUE TITLE
Full UnixFS DAG construction support

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#147]
Tracking issue to follow our support for creating UnixFS files, directories with iroh

* [x] Create files of "any" size
* [x] Create files within a directory
* [x] Proper file size accounting #200 #254 
* [x] Recursive subdirectories `kubo add -r $DIR`
* [x] Can create symlinks
* [ ] ~~Exposed as a library-level primitive~~
* [ ] ~~Integration test that confirms kubo can open a multi-block file in doubly-nested directory created with iroh~~
* [x] adding works via `irohctl`
