### ISSUE TITLE
Epic: library cleanup for better writing small examples like dumbpipe and sendme

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1878]
- [ ] Move ticket trait to iroh-common
- [ ] Implement node ticket in iroh-net https://github.com/n0-computer/iroh/issues/1860
- [ ] Ticket versioning https://github.com/n0-computer/iroh/issues/1732
- [ ] Move essential iroh-bytes utils from iroh into iroh-bytes
- [ ] Simpler way to get data like connection ALPN and remote node id
