### ISSUE TITLE
release process documention

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#248]
we need a checklist of what goes into the actual release process. 

This is not the *content* that goes into a release, but the specific things that need to get done to *do* a release.

- [x] document how to generate the changelog
- [x] figure out what tool actually cuts the git release tag. Is it `cargo publish`, or github?
- [x] automate compiling binaries & zip file construction

**Comment by dignifiedquire** [comment]
@Arqu the last piece is for you I believe

**Comment by Arqu** [comment]
Binaries are build via CI.
Release zip can now be done easily with https://github.com/n0-computer/ops/blob/main/util/release_zip.sh
Uploads are manual for now.
