### ISSUE TITLE
iroh-gateway spec compatibility

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#277]
Originally we took the `go-ipfs` (now `kubo`) implementation of the gateway as the baseline of what's expected from a gateway. Since then [this spec](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#path-gateway-specification) came out and we should aim to comply with it as much as possible (which will also lead us to sand down some of our rough edges). 

From the spec so far we're missing:
- [x] `HEAD` support
- [x] Proper ETag and Cache control handling
- [x] Support for `Range` header/reqs
- [x] Review `Accept-Headers`
- [x] Double check `Service-Worker` handling
- [x] Align/simplify request url `?params`
- [x] Audit response headers
- [x] Adjust responses and response codes to be in line with spec

Issues we already have that cross over into it or are appropriate improvements:
- [x] https://github.com/n0-computer/iroh/issues/230
- [x] https://github.com/n0-computer/iroh/issues/103
- [x] https://github.com/n0-computer/iroh/issues/96
- [x] https://github.com/n0-computer/iroh/issues/197
- [x] https://github.com/n0-computer/iroh/issues/98
- [x] https://github.com/n0-computer/iroh/issues/130
- [x] https://github.com/n0-computer/iroh/issues/92
- [ ] https://github.com/n0-computer/iroh/issues/97
- [x] https://github.com/n0-computer/iroh/issues/89

Punting due to other priorities:
- [x] https://github.com/n0-computer/iroh/issues/93
- [x] https://github.com/n0-computer/iroh/issues/99

Potential extensions:
- https://github.com/ipfs/specs/pull/288

**Comment by Arqu** [comment]
range reqs https://github.com/n0-computer/iroh/pull/330

**Comment by Arqu** [comment]
Missing 404 handling / templates for completion.

**Comment by Arqu** [comment]
closing in favor of https://github.com/n0-computer/iroh/issues/465
