### ISSUE TITLE
CLI overview issue

### ISSUE THREAD

**Issue by faassen** [n0-computer/iroh#284]
- [x] #267
- [x] ~~#268~~
- [x] #269 in PR review
- [x] #270 minor improvements in API in draft PR
- [x] #271
- [x] #290  in progress by @b5 
- [x] #308
- [x] ~~#272~~
- [x] #274
- [x] #281 
- [x] #282
- [x] #263
- [x] #291
- [ ] #295 
- [x] #309 
- [x] ~~#310~~
- [ ] #312 
- [x] #313 
- [ ] #345 
- [ ] #344 

A reference branch for the CLI: https://github.com/n0-computer/iroh/tree/b5/cli_docs_spike/iroh/src

**Comment by b5** [comment]
hihg-level help output from my [CLI code spike branch]()

```
$ iroh
iroh
A next generation IPFS implementation: https://iroh.computer

USAGE:
    iroh <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -v, --version    print version information

SUBCOMMANDS:
    add       Add a file to IPFS
    get       get things
    help      Print this message or the help of the given subcommand(s)
    p2p       peer-2-peer commands
    start     start a long running IPFS process
    status    report current status of iroh
```

p2p command subcommand:
```
iroh-p2p
peer-2-peer commands

USAGE:
    iroh p2p <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    connect    connect to a peer
    help       Print this message or the help of the given subcommand(s)
    id         show IPFS node id info
```

note that we're _not_ requiring `iroh p2p disconnect` for this release

**Comment by b5** [comment]
initial commands are implemented. closing!
