### ISSUE TITLE
Implement QUIC Address discovery

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#2842]
Currently, STUN packets are sent as raw UDP packets. We've run into situations in the wild where STUN packets get dropped due to high latency or congestion. Since STUN packets tell us what our own public IP address is, when these packets get lost, we no don't know our own address, and therefore can't tell other's what our dialable addresses are. 

Doing address discovery over QUIC rather than through the usual STUN / UDP process does two things:
1) QUIC connections have guaranteed delivery. In highly congested / low latency networks, we will still get our public addresess.

2) QUIC connections are encrypted! No more leaking your public address information for anyone to peak at.

Our plan is to implement [QUIC Address Discovery](https://marten-seemann.github.io/draft-seemann-quic-address-discovery/draft-seemann-quic-address-discovery.html), which replaces the functionality of STUN with a new protocol that runs over a QUIC connection.

This work will happen in a few phases:

- [x] implement QUIC Address Discovery in iroh-quinn, our fork of quinn
       https://github.com/n0-computer/quinn/pull/12
- [x] interop tests with picoquic
- [x] integrating QUIC Address Discovery into iroh-relay
- [x] integrating QUIC Address Discovery into net-report

**Comment by dignifiedquire** [comment]
@ramfox can we close this?
