### ISSUE TITLE
"no p2p service" feedback tracking issue

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#399]
Let's track the state where the p2p node is unavailable, and up the

- [ ] ~~running `iroh add` should still work, ingesting locally. Needs to warn the user that content won't be provided to the network without running p2p.~~
- [x] `iroh add` should warn the user they need to be online.
- [x] **all** p2p subcommands should present `p2p service is not running` error message when run without the p2p service
- [ ] `iroh get` without any remote resolvers should error out & inform the user they need either a gateway or p2p running
