### ISSUE TITLE
end-2-end test tracking issue

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#453]
### Data transport e2e tests
- [ ] single node: create a random directory, add/get roundtrip
- [ ] single node: create a random file, add/get roundtrip
- [ ] single node: massively nested directory add/get roundtrip
- [ ] 2 nodes: add in one place, get from another

### e2e testing CLI command user stories
- [ ] start, status, stop, status
- [ ] p2p lookup, peers, connect

### Crates that need e2e coverage
- [ ] `iroh-api`

### Test Requirements
* tests should execute fast. We expect any given e2e test to execute within a second
* we'll run all e2e tests on all PRs for now
* allow manual trigger
* rust has an ignore test feature, use that for long-running tests, you can run them if you pass `cargo test --ignored`
* run ignored tests in release mode on CI `cargo test --ignored --release` to execute them fast
* e2e tests should live in a `tests` folder next to your source folder. See [rust docs](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests)
* prop tests are allowed to take a while, should be run on a second tier
* we can extract concrete tests from a proptest

**Comment by glitchy** [comment]
just a thought--when i think of e2e tests i think func tests more than strict integration tests--thoughts about creating a separate func test suite at iroh root that spins everything up (compose), tests e2e functionality, and tears down?
