### ISSUE TITLE
p2p unit tests

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#455]
we need to mock p2p connections. irritating, but required.

Let's write a unit test for each rpc method. make sure it's control flow is correct.

- [x] ExternalAddrs
- [x] LocalPeerId
- [ ] ~~BitswapRequest~~ (move to bitswap specific testing work)
- [ ] ~~BitswapNotifyNewBlocks~~ (move to bitswap specific testing work)
- [ ] ~~BitswapStopSession~~ (move to bitswap specific testing work)
- [x] ProviderRequest
- [x] StartProviding
- [x] StopProviding
- [x] NetListeningAddrs
- [x] NetPeers
- [x] NetConnectByPeerId
- [x] NetConnect
- [ ] ~~NetDisconnect~~ (not implemented)
- [x] Gossipsub
- [x] FindPeerOnDHT
- [x] LookupPeerInfo
- [x] ListenForIdentify
- [ ] CancelListenForIdentify
- [x] AddressesOfPeer
- [ ] ~~Shutdown~~ (Not implemented)

**Comment by ramfox** [comment]
I'm proposing we re-focus this issue to be more general: "p2p tests", rather than "unit tests". Our node story, currently, is a bit too complicated to fully isolate the nodes from the (local) network.

While making decisions about how to test the p2p node, I did a little journey into seeing how other crates that import libp2p test their work.

## how tf do people test the p2p node

From doing an audit of crates that import libp2p, most folks don't use it as intensely as we do. Testing libp2p interactions, in certain cases, is as simple as dropping in a mock `NetworkBehavior` and ensuring that things run.

The other main method I've seen is:
- use actual nodes with their actual network behaviors
- try to limit exposure to the network (either by having no bootstrap nodes, or prescribing specific bootstrap nodes, usually the other nodes in the test)
- write tests that are more "integration-y", since you are testing interactions between nodes and not just isolating specific functions

## we have a convoluted node story
The main thing we are trying to test, in our case, is that when an `RpcMessage` or a `NetworkEvent` is sent to the node to handle, the node takes the expected actions.

We rely on one-shot channels to communicate from the node to the outside caller. These channels are stored in various vectors and hashmaps separated by concern. The tests we _really_ want here, just ensure that when an `RpcMessage`
or `NetworkEvent` is processed by the node, we are properly responding to these triggers, and adding, sending, or removing these oneshot channels

To isolate only these pieces & "unit test" these components, we would need to:
- refactor the swarm as a trait, "hiding" the complex network behaviour interactions behind more-easily mocked methods, so we can focus only on the interactions between these messages/events and their corresponding oneshot channels
- create a test swarm that allows you to inject network events & mock network behaviour
- build a test node that uses the test swarm.
- inject `RpcMessage`s and ensure the node changes its state correctly
- inject `NetworkEvent`s and ensure the node changes its state correctly

However, doing this would take quite a bit of refactoring and I want to have tests in place before doing any refactoring. It's a bit of a chicken-and-egg situation. 

So instead of the "trait & mock" route, I instead followed the other pattern: build nodes with limited exposure to the outside network & test their interactions.

## TestRunner
- We now have a `TestRunner` that can build, run, and drop a node, and gives
  access to the associated rpc client.
- We can inject kademlia records to a node so that it is able to "provide", so we can test the behavior of "finding" a node or a cid on the network.
- This will give us some amount of assurance that we can make refactors & not break expected behaviour

## future unit tests?
I wanted to give a bit more detail about the most important bits to test in our
node: the `handle_rpc_message` and `handle_swarm_event` methods. 

These are somewhat symmetrical. An RPC message will trigger some action in the node, usually making a call to some network
behavior. This network behaviour can sometimes trigger a `SwarmEvent`, which gets handled in `handle_swarm_event`.

The key thing here is that we need to keep both sides of the reflection separate when testing: sending an `RpcMessage::NetConnect` message should add a `dial_query` to the node, and should trigger a mock call to `swarm.dial`, it shouldn't actually dial or expect to handle the incoming network events. The other side of this interaction, which comes from the network (a `SwarmEvent::OutgoingConnection` event) should be injected in a separate test, and ensure that it pulls the correct `dial_query` from the list & sends a response over the channel.
       
## open ports
The "open port" issue still remains a problem that different projects have
different ways of dealing with.

Full discloser: I've side-stepped that issue for the immediate moment & hard wired the ports. I just wanted to mention a new way I've seen a project deal with this issue:

They make a tcp connection with port `0`, record the port that was assigned, and then close that connection. They then add that port as the port number for the libp2p node. It seems like this can come with a few possible errors:
- the OS doesn't release the port quickly enough to then use in the test node
- another process can grab that open port between the time the tcp connection
  closes and we request using that port in the test node

**Comment by ramfox** [comment]
yes:
https://github.com/paritytech/substrate/
https://github.com/ChainSafe/forest
https://github.com/ljedrz/pea2pea
https://github.com/sigp/lighthouse

**Comment by dignifiedquire** [comment]
Given the refocus, this shouldn't be closed?

**Comment by ramfox** [comment]
Okay, but removing the milestone for `0.1.1`
