### ISSUE TITLE
publish iroh workspace on crates.io

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#457]
We want to get our code out into rustacean land on crates.io. This is just for rust developers. We're rounding out our release process in #248

- [x] need to not run a libp2p fork
- [x] cut a release
- [x] set up a release process for publishing our workspace (according to dig this is nontrivial)
- [x] add publication documentation to a [releases doc](https://github.com/ipfs/kubo/blob/master/docs/releases.md)
- [ ] publish said release
  - [x]  [iroh-car@0.1.2](https://crates.io/crates/iroh-car)
  - [x]  [iroh-util@0.1.2](https://crates.io/crates/iroh-util)
  - [x]  [iroh-metrics@0.1.2](https://crates.io/crates/iroh-metrics)
  - [x]  [iroh-rpc-types@0.1.2](https://crates.io/crates/iroh-rpc-types)
  - [x]  [iroh-rpc-client@0.1.2](https://crates.io/crates/iroh-rpc-client)
  - [x]  [iroh-resolver@0.1.2](https://crates.io/crates/iroh-resolver)
  - [x]  [iroh-store@0.1.2](https://crates.io/crates/iroh-store)
  - [x]  [iroh-api@0.1.2](https://crates.io/crates/iroh-api)
  - [x]  [iroh-localops@0.1.2](https://crates.io/crates/iroh-localops)
  - [x]  [iroh@0.1.2](https://crates.io/crates/iroh)
  - [x]  [iroh-bitswap@0.1.2](https://crates.io/crates/iroh-bitswap)
  - [x]  [iroh-gateway@0.1.2](https://crates.io/crates/iroh-gateway)
  - [x]  [iroh-p2p@0.1.2](https://crates.io/crates/iroh-p2p)
  - [ ]  [iroh-one@0.1.2](https://crates.io/crates/iroh-one)
  - [ ]  [iroh-share@0.1.2](https://crates.io/crates/iroh-share)
- [ ] close this issue
- [ ] party

**Comment by dignifiedquire** [comment]
Ref #560

**Comment by dignifiedquire** [comment]
publishing in progress

- [x]  [iroh-car@0.1.2](https://crates.io/crates/iroh-car)
- [x]  [iroh-util@0.1.2](https://crates.io/crates/iroh-util)
- [x]  [iroh-metrics@0.1.2](https://crates.io/crates/iroh-metrics)
- [x]  [iroh-rpc-types@0.1.2](https://crates.io/crates/iroh-rpc-types)
- [x]  [iroh-rpc-client@0.1.2](https://crates.io/crates/iroh-rpc-client)
- [ ]  [iroh-resolver@0.1.2](https://crates.io/crates/iroh-resolver)
- [x]  [iroh-store@0.1.2](https://crates.io/crates/iroh-store)
- [ ]  [iroh-api@0.1.2](https://crates.io/crates/iroh-api)
- [ ]  [iroh-localops@0.1.2](https://crates.io/crates/iroh-localops)
- [ ]  [iroh@0.1.2](https://crates.io/crates/iroh)
- [ ]  [iroh-bitswap@0.1.2](https://crates.io/crates/iroh-bitswap)
- [ ]  [iroh-gateway@0.1.2](https://crates.io/crates/iroh-gateway)
- [ ]  [iroh-p2p@0.1.2](https://crates.io/crates/iroh-p2p)
- [ ]  [iroh-one@0.1.2](https://crates.io/crates/iroh-one)
- [ ]  [iroh-share@0.1.2](https://crates.io/crates/iroh-share)

**Comment by dignifiedquire** [comment]
Unable to publish `iroh-share` and `iroh-one` due to issues with `git-version`. Will release PR a fix and publish `0.1.3`

**Comment by dignifiedquire** [comment]
- [x]  [iroh-car@0.1.3](https://crates.io/crates/iroh-car)
- [x]  [iroh-util@0.1.3](https://crates.io/crates/iroh-util)
- [x]  [iroh-metrics@0.1.3](https://crates.io/crates/iroh-metrics)
- [x]  [iroh-rpc-types@0.1.3](https://crates.io/crates/iroh-rpc-types)
- [x]  [iroh-rpc-client@0.1.3](https://crates.io/crates/iroh-rpc-client)
- [x]  [iroh-resolver@0.1.3](https://crates.io/crates/iroh-resolver)
- [x]  [iroh-store@0.1.3](https://crates.io/crates/iroh-store)
- [x]  [iroh-api@0.1.3](https://crates.io/crates/iroh-api)
- [x]  [iroh-localops@0.1.3](https://crates.io/crates/iroh-localops)
- [x]  [iroh@0.1.3](https://crates.io/crates/iroh)
- [x]  [iroh-bitswap@0.1.3](https://crates.io/crates/iroh-bitswap)
- [x]  [iroh-gateway@0.1.3](https://crates.io/crates/iroh-gateway)
- [x]  [iroh-p2p@0.1.3](https://crates.io/crates/iroh-p2p)
- [x]  [iroh-one@0.1.3](https://crates.io/crates/iroh-one)
- [x]  [iroh-share@0.1.3](https://crates.io/crates/iroh-share)

**Comment by dignifiedquire** [comment]
It is done 🎉
