### ISSUE TITLE
Derp server impl

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#833]
- [x] struct `ClientSet`
- [x] struct `Clients`
- [x] serve loop
- [x] accept (and accept server/client handshake)
- [x] mesh peers (watchers)
- [x] shutting down clients
- [x] test relay: spin up two clients, manually connect them to the server, send packets!

**Comment by dignifiedquire** [comment]
main impl is all merged into #830
